#!/bin/bash

# Based on the git hooks from IPython

git submodule init
git submodule update

if [[ "$(basename $0)" == "post-merge" ]]; then
  PREVIOUS_HEAD=ORIG_HEAD
else
  PREVIOUS_HEAD=$1
fi

# if nbextension changed, copy it to nbextensions
if [[
  ! -z "$(git diff $PREVIOUS_HEAD nbextensions/nbgrader.css)"
  && ! -z "$(git diff $PREVIOUS_HEAD nbextensions/nbgrader.js)"
]]; then
  echo "updating nbextension"
  cp nbextensions/* $(ipython locate)/nbextensions
fi
