version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3"
    nodejs: "20"
sphinx:
  builder: html
  configuration: nbgrader/docs/source/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
