#!/usr/bin/env python

import sys
import os
import subprocess

if len(sys.argv) > 1:
    group = sys.argv[1]
else:
    group = None

if group == 'js':
    print("Running javascript tests...")
    pth = os.path.abspath("nbgrader/tests/js")
    subprocess.call(["iptest", "js/{}".format(pth)])

else:
    print("Running nosetests...")
    subprocess.call("nosetests")
