.PHONY: clean user_guide command_line_tools

all: clean user_guide command_line_tools

user_guide:
	make -C user_guide

command_line_tools:
	make -C command_line_tools

clean:
	make -C user_guide clean
	make -C command_line_tools clean
