#!/bin/bash

pip install .

nbgrader quickstart example_course

mkdir example_course_exchange

chmod ugo+rw example_course_exchange

cp binder/jupyter_config.json ./jupyter_config.json

cd example_course

echo 'c.Exchange.root = "../example_course_exchange/"' >> nbgrader_config.py
